#define IDI_SCREENSAVER                 107
#define IDS_APPNAME                     130
#define IDC_SLIDER_NUMOFSTARS           1000
#define IDC_SLIDER_INTERVAL             1001
#define IDC_TEXT_NUMOFSTARS             1002
#define IDC_TEXT_INTERVAL               1003
#define IDC_BUTTON_DEFAULT              1004
#define DLG_SCRNSAVECONFIGURE           2003
#define IDC_STATIC                      -1
